"""
io_utils/clinical_io.py

Two responsibilities, kept intentionally separate:

1. Read-only lookup into the lab's existing merged_surgical_data_v2.csv
   (EMR-derived outcomes: POPF, gland texture, FRS, etc.) joined by
   case_id. Annotators can *view* this for context but the GUI never
   writes back into this file -- it's chart-review data, not something
   generated by video annotation.

2. Scoring entries that annotators generate from watching video --
   OSATS/RSS/GEARS/etc case-level subitems and PJ/yank/curve/etc
   stitch-level subitems, one row per subitem (same shape for both
   levels: case_id, case_type, video_id_annot [blank for case-level],
   rater, scale, item, hogg_var, score, start, stop, notes). This
   one-row-per-subitem shape is what lets any procedure's rubric (see
   core.config.RUBRICS) write through the same generic path with no
   rubric-specific code here -- see widgets/preprocessing_tab.py's
   `_append_score_values` / `_save_case_scores` and
   widgets/existing_clips_tab.py.

   Each CASE writes to its OWN file -- clinical/score_entries_<case_id>.csv
   -- so everything about one case's scoring lives together and is easy
   to find/share/audit on its own, regardless of how many stitches or
   raters are involved. `load_score_entries` with no case_id merges every
   such file for the Clinical tab's "all cases" review.

   Saving uses UPSERT semantics, not blind append: a new value for the
   same (case_id, video_id_annot, hogg_var, rater) replaces the old one in
   place. This is what lets a resident load an already-scored clip, change
   a value, and save again without accumulating stale duplicate rows --
   see widgets/existing_clips_tab.py's "Load existing scores" / re-save
   workflow.

PII (MRN, Progressive_Number) is filtered out of every read path used by
the GUI display layer -- see core.config.PII_COLUMNS.
"""
from __future__ import annotations
import csv
import re
from pathlib import Path
from typing import Optional

import pandas as pd

from core.config import PII_COLUMNS, SAFE_CASE_KEY, CLINICAL_DISPLAY_FIELDS

# NOTE: pcaso_var, key_step, pd_curve, pd_yank, j_curve, j_yank used to be
# dedicated columns from an earlier "one combined row per stitch" scheme.
# Every score is now its own row (scale/item/hogg_var/score), which made
# those columns permanently blank dead weight -- removed. `start`/`stop`
# are kept and get populated (the stitch's start/end offset into the
# original video, in seconds) for stitch-level rows, when known.
SCORE_ENTRIES_COLUMNS = [
    "case_id", "case_type", "video_id_annot", "rater", "scale", "item",
    "hogg_var", "score", "start", "stop", "notes",
]

# Upsert key: a new entry replaces any existing row matching all of these
# fields, rather than accumulating a duplicate. Rater is included so two
# different raters' scores for the same stitch/subitem don't clobber each
# other.
_UPSERT_KEY_FIELDS = ("video_id_annot", "hogg_var", "rater")

_LEGACY_COMBINED_FILENAME = "score_entries.csv"


def load_clinical_csv(csv_path: Path) -> pd.DataFrame:
    if not csv_path.exists():
        return pd.DataFrame()
    df = pd.read_csv(csv_path, low_memory=False)
    drop_cols = [c for c in df.columns if c in PII_COLUMNS]
    if drop_cols:
        df = df.drop(columns=drop_cols)
    return df


def case_ids(df: pd.DataFrame) -> list[str]:
    if SAFE_CASE_KEY not in df.columns:
        return []
    return sorted(df[SAFE_CASE_KEY].dropna().astype(str).unique().tolist())


def case_display_row(df: pd.DataFrame, case_id: str) -> dict:
    """One de-duplicated, PII-free dict of context fields for `case_id`,
    for read-only display in the Clinical tab."""
    if df.empty or SAFE_CASE_KEY not in df.columns:
        return {}
    sub = df[df[SAFE_CASE_KEY].astype(str) == str(case_id)]
    if sub.empty:
        return {}
    row = sub.iloc[0]
    out = {}
    for field in CLINICAL_DISPLAY_FIELDS:
        if field in row.index:
            val = row[field]
            out[field] = None if pd.isna(val) else val
    return out


def _safe_slug(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9_-]+", "_", text.strip())


def score_entries_path(clinical_dir: Path, case_id: Optional[str] = None) -> Path:
    """Path to the score-entries CSV for a given case, e.g.
    clinical/score_entries_pehCase1.csv. With no case_id, returns the
    legacy combined-file path (only relevant as a fallback if an entry
    somehow has no case_id set, which shouldn't normally happen)."""
    if case_id:
        return clinical_dir / f"score_entries_{_safe_slug(case_id)}.csv"
    return clinical_dir / _LEGACY_COMBINED_FILENAME


def all_score_entry_files(clinical_dir: Path) -> list[Path]:
    """Every score-entries file present -- one per case, plus the legacy
    combined file if it exists (e.g. from a project created before this
    per-case split, or an earlier per-case-type split)."""
    if not clinical_dir.exists():
        return []
    files = sorted(clinical_dir.glob("score_entries_*.csv"))
    legacy = clinical_dir / _LEGACY_COMBINED_FILENAME
    if legacy.exists():
        files.append(legacy)
    return files


def _read_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def _write_rows(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=SCORE_ENTRIES_COLUMNS)
        w.writeheader()
        for row in rows:
            w.writerow({col: row.get(col, "") for col in SCORE_ENTRIES_COLUMNS})


def append_score_entry(clinical_dir: Path, entry: dict) -> None:
    """Upserts `entry` into its case's score file: replaces any existing
    row with the same (video_id_annot, hogg_var, rater) instead of
    appending a duplicate, so re-saving an edited score updates it in
    place. (Function name kept for backward compatibility with existing
    call sites -- despite the name, this has upsert semantics.)"""
    path = score_entries_path(clinical_dir, entry.get("case_id"))
    rows = _read_rows(path)
    new_row = {col: str(entry.get(col, "")) for col in SCORE_ENTRIES_COLUMNS}
    new_key = tuple(new_row.get(f, "") for f in _UPSERT_KEY_FIELDS)
    for i, r in enumerate(rows):
        existing_key = tuple(str(r.get(f, "")) for f in _UPSERT_KEY_FIELDS)
        if existing_key == new_key:
            rows[i] = new_row
            break
    else:
        rows.append(new_row)
    _write_rows(path, rows)


def get_score_value(clinical_dir: Path, case_id: str, video_id_annot: str,
                     hogg_var: str, rater: str) -> Optional[str]:
    """Looks up a single previously-saved score (as a raw string -- caller
    converts), or None if nothing's been saved yet for this exact
    (video_id_annot, hogg_var, rater) combination. Used to prefill a
    dropdown with an existing value when a resident reopens a clip."""
    path = score_entries_path(clinical_dir, case_id)
    for r in _read_rows(path):
        if (str(r.get("video_id_annot", "")) == str(video_id_annot)
                and str(r.get("hogg_var", "")) == str(hogg_var)
                and str(r.get("rater", "")) == str(rater)):
            score = r.get("score", "")
            return score if score not in ("", None) else None
    return None


def load_score_entries(clinical_dir: Path, case_id: Optional[str] = None) -> pd.DataFrame:
    """With a case_id, loads just that case's file. With none, merges
    every score-entries file found (every case + any legacy combined
    file) for a project-wide view."""
    if case_id:
        path = score_entries_path(clinical_dir, case_id)
        if not path.exists():
            return pd.DataFrame(columns=SCORE_ENTRIES_COLUMNS)
        return pd.read_csv(path)

    frames = []
    for path in all_score_entry_files(clinical_dir):
        try:
            frames.append(pd.read_csv(path))
        except pd.errors.EmptyDataError:
            continue
    if not frames:
        return pd.DataFrame(columns=SCORE_ENTRIES_COLUMNS)
    return pd.concat(frames, ignore_index=True, sort=False)
