"""
io_utils/clinical_io.py

Two responsibilities, kept intentionally separate:

1. Read-only lookup into the lab's existing merged_surgical_data_v2.csv
   (EMR-derived outcomes: POPF, gland texture, FRS, etc.) joined by
   case_id. Annotators can *view* this for context but the GUI never
   writes back into this file -- it's chart-review data, not something
   generated by video annotation.

2. Append-only scoring entries that annotators *do* generate from
   watching video -- OSATS/RSS/GEARS/etc case-level subitems and
   PJ/yank/curve/etc stitch-level subitems, one row per subitem (same
   shape for both levels: case_id, case_type, video_id_annot [blank for
   case-level], rater, scale, item, hogg_var, score). This one-row-per-
   subitem shape is what lets any procedure's rubric (see core.config.
   RUBRICS) write through the same generic path with no rubric-specific
   code here -- see widgets/preprocessing_tab.py's `_append_scores`.

PII (MRN, Progressive_Number) is filtered out of every read path used by
the GUI display layer -- see core.config.PII_COLUMNS.
"""
from __future__ import annotations
import csv
from pathlib import Path
from typing import Optional

import pandas as pd

from core.config import PII_COLUMNS, SAFE_CASE_KEY, CLINICAL_DISPLAY_FIELDS

SCORE_ENTRIES_COLUMNS = [
    "case_id", "case_type", "video_id_annot", "rater", "scale", "item", "hogg_var",
    "pcaso_var", "key_step", "start", "stop", "score",
    "pd_curve", "pd_yank", "j_curve", "j_yank", "notes",
]


def load_clinical_csv(csv_path: Path) -> pd.DataFrame:
    if not csv_path.exists():
        return pd.DataFrame()
    df = pd.read_csv(csv_path, low_memory=False)
    drop_cols = [c for c in df.columns if c in PII_COLUMNS]
    if drop_cols:
        df = df.drop(columns=drop_cols)
    return df


def case_ids(df: pd.DataFrame) -> list[str]:
    if SAFE_CASE_KEY not in df.columns:
        return []
    return sorted(df[SAFE_CASE_KEY].dropna().astype(str).unique().tolist())


def case_display_row(df: pd.DataFrame, case_id: str) -> dict:
    """One de-duplicated, PII-free dict of context fields for `case_id`,
    for read-only display in the Clinical tab."""
    if df.empty or SAFE_CASE_KEY not in df.columns:
        return {}
    sub = df[df[SAFE_CASE_KEY].astype(str) == str(case_id)]
    if sub.empty:
        return {}
    row = sub.iloc[0]
    out = {}
    for field in CLINICAL_DISPLAY_FIELDS:
        if field in row.index:
            val = row[field]
            out[field] = None if pd.isna(val) else val
    return out


def score_entries_path(clinical_dir: Path) -> Path:
    return clinical_dir / "score_entries.csv"


def append_score_entry(clinical_dir: Path, entry: dict) -> None:
    path = score_entries_path(clinical_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    row = {col: entry.get(col, "") for col in SCORE_ENTRIES_COLUMNS}
    file_exists = path.exists()
    with open(path, "a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=SCORE_ENTRIES_COLUMNS)
        if not file_exists:
            w.writeheader()
        w.writerow(row)


def load_score_entries(clinical_dir: Path) -> pd.DataFrame:
    path = score_entries_path(clinical_dir)
    if not path.exists():
        return pd.DataFrame(columns=SCORE_ENTRIES_COLUMNS)
    return pd.read_csv(path)
